trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: CreateEC2Instance
  displayName: Create EC2 Instance
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
  - script: |
      # Install AWS CLI
      pip install awscli --upgrade --user
      
      # Configure AWS CLI with your credentials
      aws configure set aws_access_key_id ASIATUYJP7SUCL7P54HN
      aws configure set aws_secret_access_key ElsbaVA5MvGJWcz1ulhzFuMCGAEmbVqoa2vf9gfr
      aws configure set aws_session_token IQoJb3JpZ2luX2VjEF4aCXVzLWVhc3QtMSJHMEUCIQCw1nkkp7Lm6jjroZSL+/TKzQVcKxdx0gn7ObiyxD98jgIgV18KZjcRiJUmQhrnXoFzs10zM31uPVlIRfiMjHgwm2cqhAQIFxADGgwyNTA3Mzg2Mzc5OTIiDKCWehlIgSIq9c9jlSrhAwICGcVc/dv6E2Aa5IvV/oYcvdss/qMudWbbGOeSQM67lxzkl3EP1AwnJD7hG4nUx+eXZs37QJfIB8g1gdDl5nX/U6eGdeCe88ljaV6QkgnmUuCns2ZS2dpFmmR6c7XLIzkZDbUi4PDBlowZdhOh1Qvc0/elYKgdks9tVQs/QLbtUXNjv8SVxq2HURz+Rbaq5An5YU3N3QZ54jHh6SjNQ4OxmtyoaganN3cXdF0pscjWZXZIZN0rSLi3GxyxPzYakvd8llqomyEzU+gkI+m5i3lqh+G8iKmFH0Ml3r1xTXpcHnjOlOBhmySJAcakIk0VgFo/fmc64tcjYpEipJ9F0xzjLOcwMWjYoXaij+EjF1SwMtuMxB7/z0h9cPkI+Sh28qm7FnbDUCqztXD69LrV7YF5nWAtpciutRNJ/I8mEMBiMoDeloM/YYElh7+pDFOz36yINlKJf62Bwbq1VSw/8xfNQvtaBPIO4EOlPcDikf3aVqurZXcXFCNDaaVKB1oCNHdhhkt556o7JtiGsa1UTddXjZ9lN+qMSXjH/71ykDgbVzcwU9oVl/+5e+gcBGyhgBtFIGsK5FYwJ72sdhtWqhWZNWpXi+JCsGtXZdgZLaAqX2eZBHn/J/gMPpMiHhrYxtsw07TjpgY6pgFEazAxFysuM5dqU46faYzBK5vgF1FzP6WPglKBTwbGl7M+Dp8ofWoUtSp96C2tuSsC9C9Sh2VO8dYiT6V8i7AZbrOOcQ6URBXLZ/j/d68IYKjfVsu40UJNn5JFVwN+desZ2rMyBm2p8lY5EQyixDaxiaev3ZRw5L06LRkjEjr1RRctS/7o3YHiBKFU0p1SNaTRre42v7J5ZAX5UpyQHpRvXmEyVIBV
      aws configure set default.region us-east-1
      
      # Create EC2 instance
      instance_id=$(aws ec2 run-instances --image-id ami-08a52ddb321b32a8c --instance-type t2.micro --key-name Nikita-21224811 --query 'Instances[0].InstanceId' --output text)
      
      # Wait for instance to be running
      aws ec2 wait instance-running --instance-ids $instance_id
    displayName: Create EC2 Instance
